CREATE TABLE Cities(
CityID INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(30) NOT NULL,
CountryID INT NOT NULL,
IsActive BIT NOT NULL DEFAULT(1),
CreateDate DATETIME NOT NULL DEFAULT(GETDATE()),
UpdateDate DATETIME NULL,
FOREIGN KEY (CountryID) REFERENCES Countries(CountryID)
)