CREATE TABLE Employees(
	EmployeeID INT PRIMARY KEY IDENTITY(1,1),
	FirstName NVARCHAR(30) NOT NULL,
	LastName NVARCHAR(32) NOT NULL,
	Email VARCHAR(50) UNIQUE NOT NULL CHECK(Email LIKE '%_@__%.__%'),
	AddressLine1 NVARCHAR(100) NOT NULL,
	AddressLine2 NVARCHAR(100) NULL,
	TourID INT NOT NULL REFERENCES Tours(TourID),
	PhoneNumber VARCHAR(24),
	BirthDate DATE NOT NULL,
	HireDate DATE NOT NULL,
	PositionID INT NOT NULL REFERENCES Positions(PositionID),
	IsActive BIT NOT NULL DEFAULT(1),
	CreateDate DATETIME NOT NULL DEFAULT(GETDATE()),
	UpdateDate DATETIME NULL
);
