CREATE TABLE Hotels(
HotelID INT PRIMARY KEY IDENTITY(1,1),
CityID INT NOT NULL,
Name NVARCHAR(40) NOT NULL,
Stars INT NOT NULL CHECK (Stars > 0 AND Stars <= 5),
PerNightPrice MONEY NOT NULL CHECK (PerNightPrice > 0),
Dining BIT NOT NULL,
AdditionalServices VARCHAR(1000) NULL,
IsActive BIT NOT NULL DEFAULT(1),
CreateDate DATETIME NOT NULL DEFAULT(GETDATE()),
UpdateDate DATETIME NULL
FOREIGN KEY (CityID) REFERENCES Cities(CityID)
)