CREATE TABLE Orders(
OrderID INT PRIMARY KEY IDENTITY(1,1),
TouristID INT NOT NULL,
TourID INT NOT NULL,
NumberOfPeople INT NOT NULL CHECK (NumberOfPeople > 0), 
TotalPrice MONEY NOT NULL CHECK (TotalPrice > 0),    
IsPaid BIT NOT NULL DEFAULT(0),
PaymentDate DATETIME NULL,    
IsActive BIT NOT NULL DEFAULT(1), 
CreateDate DATETIME NOT NULL DEFAULT(GETDATE()),
UpdateDate DATETIME NULL,
FOREIGN KEY (TouristID) REFERENCES Tourists(TouristID),
FOREIGN KEY (TourID) REFERENCES Tours(TourID)
);