CREATE TABLE Tours(
TourID INT PRIMARY KEY IDENTITY(1,1),
Name NVARCHAR(20) NOT NULL,
Duration INT NOT NULL CHECK (Duration > 0),
TotalPrice MONEY NOT NULL,
StartDate DATE NOT NULL,
EndDate DATE NOT NULL,
IsActive BIT NOT NULL DEFAULT(1),
CreateDate DATETIME NOT NULL DEFAULT(GETDATE()),
UpdateDate DATETIME NULL
)