CREATE TABLE Tourists(
TouristID INT PRIMARY KEY IDENTITY(1,1),
TourID INT NOT NULL,
FirstName NVARCHAR(30) NOT NULL,
LastName NVARCHAR(40) NOT NULL,
BirthDate DATE NOT NULL,
ContactPhone VARCHAR(50) NOT NULL,
IsActive BIT DEFAULT(1) NOT NULL,
CreateDate DATETIME NOT NULL DEFAULT(GETDATE()),
FOREIGN KEY (TourID) REFERENCES Tours(TourID)
)