CREATE TABLE TourStops (
TourStopID INT PRIMARY KEY IDENTITY(1,1),
TourID INT NOT NULL,
CityID INT NOT NULL,
DaysSpent INT NOT NULL CHECK (DaysSpent > 0),
IsActive BIT NOT NULL DEFAULT(1),
CreateDate DATE NOT NULL DEFAULT(GETDATE()),
UpdateDate DATE NULL,
FOREIGN KEY (TourID) REFERENCES Tours(TourID),
FOREIGN KEY (CityID) REFERENCES Cities(CityID)
)